import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-agricultural-input-rebate-recovery",
  "engine": "recovery",
  "title": "Agricultural Input Rebate Recovery",
  "shortTitle": "Agricultural Input Rebate Recovery",
  "tagline": "Capture supplier rebates and loyalty incentives earned through acres, product bundles, volume, and program compliance.",
  "industry": "Agricultural Procurement Recovery",
  "buyer": "Farms, cooperatives, and agricultural retailers",
  "uiPort": 4710,
  "apiPort": 5710,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Agricultural Input Rebate Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits in one accountable workflow. Capture supplier rebates and loyalty incentives earned through acres, product bundles, volume, and program compliance.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Agricultural Input Rebate Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("supplier-program-library","AIR01","Supplier program library","Execute supplier program library using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed supplier program library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Supplier program library Reference","text","AIR01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("farm-account-registry","AIR02","Farm account registry","Execute farm account registry using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed farm account registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Farm account registry Reference","text","AIR02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("product-eligibility-mapping","AIR03","Product eligibility mapping","Execute product eligibility mapping using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed product eligibility mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Product eligibility mapping Reference","text","AIR03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("purchase-transaction-ingestion","AIR04","Purchase transaction ingestion","Execute purchase transaction ingestion using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed purchase transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Purchase transaction ingestion Reference","text","AIR04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("acre-application-evidence","AIR05","Acre application evidence","Execute acre application evidence using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed acre application evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Acre application evidence Reference","text","AIR05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("volume-tier-calculation","AIR06","Volume tier calculation","Execute volume tier calculation using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed volume tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Volume tier calculation Reference","text","AIR06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("product-bundle-validation","AIR07","Product bundle validation","Execute product bundle validation using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed product bundle validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Product bundle validation Reference","text","AIR07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("early-order-incentive","AIR08","Early order incentive","Execute early order incentive using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed early order incentive decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Early order incentive Reference","text","AIR08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("loyalty-status-control","AIR09","Loyalty status control","Execute loyalty status control using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed loyalty status control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Loyalty status control Reference","text","AIR09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("return-exclusion","AIR10","Return exclusion","Execute return exclusion using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed return exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Return exclusion Reference","text","AIR10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("rebate-claim-preparation","AIR11","Rebate claim preparation","Execute rebate claim preparation using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed rebate claim preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Rebate claim preparation Reference","text","AIR11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("supplier-statement-audit","AIR12","Supplier statement audit","Execute supplier statement audit using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed supplier statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Supplier statement audit Reference","text","AIR12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("dispute-workflow","AIR13","Dispute workflow","Execute dispute workflow using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Dispute workflow Reference","text","AIR13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("credit-cash-reconciliation","AIR14","Credit cash reconciliation","Execute credit cash reconciliation using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed credit cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Credit cash reconciliation Reference","text","AIR14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]}),
feature("farm-supplier-analytics","AIR15","Farm supplier analytics","Execute farm supplier analytics using seed chemical and fertilizer agreements, farms, products, purchases, acres, application records, volume tiers, bundles, loyalty programs, claims, and credits.","Produce a governed farm supplier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Farm Program","text","Supplier / Farm Program · Standard Case"],["caseReference","Farm supplier analytics Reference","text","AIR15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1428750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1728788],["domainDriver","Input Category","select","Seed",["Seed","Crop protection","Fertilizer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Farm account registry case","Product eligibility mapping case","Purchase transaction ingestion case","Acre application evidence case"]})
]);
